title: Elementary 2
description: English course!
theme: just-the-docs
color_scheme: welearn

search_enabled: false
favicon_ico: "/assets/images/favicon.ico"

logo: "/assets/images/logo.png"

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template